apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: php-secret
  namespace: php-demo
spec:
  dataFrom:
    - extract:
        key: <<SECRET_NAME_FROM_AWS>>
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: <<SECRET_STORE_NAME_CR_FROM_OPENSHIFT>> #php-secret-store
  target:
    name: php-secret
    template:
      type: Opaque