apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  annotations:
    operator-sdk/primary-resource: /externalsecret-validate
    operator-sdk/primary-resource-type: ValidatingWebhookConfiguration.admissionregistration.k8s.io
  resourceVersion: '160318'
  name: externalsecret-operator-config
  namespace: secret-manager
  finalizers:
    - helm.sdk.operatorframework.io/uninstall-release
spec:
  certController:
    nodeSelector: {}
    imagePullSecrets: []
    requeueInterval: 5m
    podLabels: {}
    resources: {}
    fullnameOverride: ''
    affinity: {}
    prometheus:
      enabled: false
      service:
        port: 8080
    podSecurityContext: {}
    extraArgs: {}
    securityContext: {}
    rbac:
      create: true
    nameOverride: ''
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    create: true
    tolerations: []
    extraEnv: []
    priorityClassName: ''
    deploymentAnnotations: {}
    podAnnotations: {}
  createOperator: true
  nodeSelector: {}
  scopedRBAC: false
  imagePullSecrets: []
  podLabels: {}
  resources: {}
  leaderElect: false
  fullnameOverride: ''
  processClusterExternalSecret: true
  affinity: {}
  prometheus:
    enabled: false
    service:
      port: 8080
  podSecurityContext: {}
  scopedNamespace: ''
  extraArgs: {}
  securityContext: {}
  rbac:
    create: true
  processClusterStore: true
  concurrent: 1
  webhook:
    nodeSelector: {}
    imagePullSecrets: []
    podLabels: {}
    resources: {}
    fullnameOverride: ''
    affinity: {}
    certCheckInterval: 5m
    certDir: /tmp/certs
    prometheus:
      enabled: false
      service:
        port: 8080
    podSecurityContext: {}
    extraArgs: {}
    securityContext: {}
    rbac:
      create: true
    replicaCount: 1
    nameOverride: ''
    serviceAccount:
      annotations: {}
      create: true
      name: ''
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/external-secrets/external-secrets
      tag: ''
    create: true
    tolerations: []
    extraEnv: []
    priorityClassName: ''
    deploymentAnnotations: {}
    podAnnotations: {}
  replicaCount: 1
  nameOverride: ''
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: '<<ROLE_ARN>>'
    create: true
    name: ''
  installCRDs: false
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/external-secrets/external-secrets
    tag: ''
  controllerClass: ''
  tolerations: []
  extraEnv: []
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
  priorityClassName: ''
  deploymentAnnotations: {}
  podAnnotations: {}